version: "3.8"
services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # Broker
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./worker_output:/app/output
    command: python app/worker.py
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2  # number of workers
      resources:
        limits:
          cpus: "0.5"  # Optional: Limit CPU usage if needed
          memory: 500M  # Optional: Limit memory usage if needed