apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ai-tools
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  DATABASE_URL: postgres://postgres:postgres@db:5432/ai-tools
